python3 main.py -source=4 -state="train" -mode="arc" -normalization="weight"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="weight" -en_type="vocal"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="weight" -en_type="bass"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="weight" -en_type="drums"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="weight" -en_type="other"
python3 main.py -source=4 -state="test" -mode="arc" -normalization="weight"
python3 main.py -source=4 -state="test" -mode="enhancement" -normalization="weight"
python3 main.py -source=4 -state="train" -mode="arc" -normalization="batch"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="batch" -en_type="vocal"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="batch" -en_type="bass"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="batch" -en_type="drums"
python3 main.py -source=4 -state="train" -mode="enhancement" -normalization="batch" -en_type="other"
python3 main.py -source=4 -state="test" -mode="arc" -normalization="batch"
python3 main.py -source=4 -state="test" -mode="enhancement" -normalization="batch"
python3 main.py -source=2 -state="train" -mode="arc" -normalization="weight"
python3 main.py -source=2 -state="train" -mode="enhancement" -normalization="weight" -en_type="vocal"
python3 main.py -source=2 -state="train" -mode="enhancement" -normalization="weight" -en_type="other"
python3 main.py -source=2 -state="test" -mode="arc" -normalization="weight"
python3 main.py -source=2 -state="test" -mode="enhancement" -normalization="weight"
python3 main.py -source=2 -state="train" -mode="arc" -normalization="batch"
python3 main.py -source=2 -state="train" -mode="enhancement" -normalization="batch" -en_type="vocal"
python3 main.py -source=2 -state="train" -mode="enhancement" -normalization="batch" -en_type="other"
python3 main.py -source=2 -state="test" -mode="arc" -normalization="batch"
python3 main.py -source=2 -state="test" -mode="enhancement" -normalization="batch"